"""init

Revision ID: 6c1608e14081
Revises: 
Create Date: 2025-02-16 17:22:00.398913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1608e14081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mantenedoras',
    sa.Column('cnpj_mantenedora', sa.String(length=14), nullable=False),
    sa.Column('nome_razao_social_mantenedora', sa.String(length=255), nullable=False),
    sa.Column('numero_telefone_mantenedora', sa.String(length=20), nullable=True),
    sa.Column('codigo_banco', sa.String(length=3), nullable=False),
    sa.Column('numero_agencia', sa.String(length=10), nullable=False),
    sa.Column('numero_conta_corrente', sa.String(length=20), nullable=False),
    sa.Column('data_criacao_mantenedora', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj_mantenedora')
    )
    op.create_table('estabelecimentos',
    sa.Column('codigo_unidade', sa.String(length=20), nullable=False),
    sa.Column('codigo_cnes', sa.String(length=20), nullable=False),
    sa.Column('cnpj_mantenedora', sa.String(length=14), nullable=False),
    sa.Column('nome_razao_social_estabelecimento', sa.String(length=255), nullable=False),
    sa.Column('nome_fantasia_estabelecimento', sa.String(length=255), nullable=False),
    sa.Column('numero_telefone_estabelecimento', sa.String(length=20), nullable=True),
    sa.Column('email_estabelecimento', sa.String(length=255), nullable=True),
    sa.Column('mantenedora_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mantenedora_id'], ['mantenedoras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_cnes'),
    sa.UniqueConstraint('codigo_unidade')
    )
    op.create_table('enderecos',
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('cep_estabelecimento', sa.String(length=8), nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estabelecimento_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enderecos')
    op.drop_table('estabelecimentos')
    op.drop_table('mantenedoras')
    # ### end Alembic commands ###
